var express = require('express');
var router = express.Router();
const MovieController = require("../controllers/movie.controller");
router.get('/get-anime-movie', MovieController.getAnimeMovie);
router.get('/get-movie-detail/:ten_dia_chi_phim', MovieController.getMovieDetail);
router.post("/add-to-favorites", MovieController.addToFavorites);
router.post('/favorites', MovieController.removeFromFavorites);
router.get("/favorites/check/:phim_id", MovieController.checkIfSaved);
router.get("/all-favorites", MovieController.getFavoriteMovies);
router.get('/get-single-movie', MovieController.getSingleMovie);
router.get('/get-series-movie', MovieController.getSeriesMovie);
router.get('/get-tv-shows', MovieController.getTVShows);
router.get("/search", MovieController.searchMovie);
router.get('/latest-movies', MovieController.getLatestMovies);
router.get('/movie-by-category', MovieController.getMovieByCategory);
router.get('/all-movie', MovieController.getAllMovies);
router.post('/add-movie', MovieController.addMovie);
router.put('/update-movie/:id', MovieController.updateMovie);
router.delete('/delete-movie/:id', MovieController.deleteMovie);
router.get('/get-movie-by/:id', MovieController.getMovieById);
module.exports = router;
